### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by Justholdme1** [GlitchImmunity/EEG-Diffusion#1]
I'm very interested in your project, I'm recently studying the generation model of EEG signals, can you send me a copy of the EEG data set you use, thank you very much.My email address is waterswimming1@gmail.com.

**Comment by GlitchImmunity** [comment]
Hello. We used the EEG dataset from here https://www.bbci.de/competition/iv/. Here is a description of the dataset. https://www.bbci.de/competition/iv/desc_2a.pdf. 

Also, just to be clear, this was for a school project. I'll continue working on improving the diffusion model it in the future, but I can't give a timeline.

Thank you for your interest!
