### ISSUE TITLE
code

### ISSUE THREAD

**Issue by Justholdme1** [GlitchImmunity/EEG-Diffusion#2]
When I ran Diffusion.ipynb I found that EEGDiffusion_Naive is not defined in the diffusion model, is it just me or is there a missing part of the code?
![image](https://user-images.githubusercontent.com/98572023/231047984-242a04c2-99f1-4b45-8f41-5dfdef10890a.png)

**Comment by GlitchImmunity** [comment]
Apologies. I'll update the repo with the correct code shortly

**Comment by GlitchImmunity** [comment]
I updated the correct code and it should run now
